# docker-compose.yml

version: "3"

services:
  mysql:
    restart: always
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: test
      MYSQL_PASSWORD: password
  php:
    # image: php:7.3-fpm
    build:
      context: .
      dockerfile: ./php-mysqli-Dockerfile
    restart: always
    volumes:
      - ./php-7.3.ini:/usr/local/etc/php/php.ini
      - ./www:/var/www
  nginx:
    image: nginx:latest
    restart: always
    links:
      - mysql
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log:/var/log/nginx
      - ./www:/var/www